export const UPDATE_HOSPITAL_CHOSEN = "UPDATE_HOSPITAL_CHOSEN";
export const UPDATE_SPECIALITY_CHOSEN = "UPDATE_SPECIALITY_CHOSEN";
export const UPDATE_CITY_CHOSEN = "UPDATE_CITY_CHOSEN";
export const UPDATE_FILTERED_DOCTORS = "UPDATE_FILTERED_DOCTORS";
export const UPDATE_DOCTORS_SORT = "UPDATE_DOCTORS_SORT";
export const UPDATE_DOCTORS_ORDER = "UPDATE_DOCTORS_ORDER";
export const UPDATE_DOCTORS_TOTAL_PAGE = "UPDATE_DOCTORS_TOTAL_PAGE";
export const UPDATE_DOCTORS_CURRENTLY_VIEWED_PAGE_NUM =
  "UPDATE_DOCTORS_CURRENTLY_VIEWED_PAGE_NUM";
export const UPDATE_DOCTORS_PREVIOUSLY_VIEWED_PAGE_NUMS =
  "UPDATE_DOCTORS_PREVIOUSLY_VIEWED_PAGE_NUMS";
export const UPDATE_TOTAL_DOCTORS = "UPDATE_TOTAL_DOCTORS";
export const UPDATE_NUM_OF_DOCTORS_PER_PAGE = "UPDATE_NUM_OF_DOCTORS_PER_PAGE";
