export const doctors_data = [
  {
    id: 1,
    name: "Dr. John Smith",
    image: "/images/doctor1.jpg",
    speciality: "Cardiology",
    experience: "10 years",
    location: "Biratnagar",
    contact: {
      phone: "+1 123 456 7890",
      email: "johnsmith@example.com",
    },
    rating: 4.8,
    reviews: 120,
    consultationFee: "$150",
  },
  {
    id: 2,
    name: "Dr. Emily Clark",
    image: "/images/doctor1.jpg",
    speciality: "Dermatology",
    experience: "8 years",
    location: "Kathmandu",
    contact: {
      phone: "+1 987 654 3210",
      email: "emilyclark@example.com",
    },
    rating: 4.7,
    reviews: 95,
    consultationFee: "$200",
  },
  {
    id: 3,
    name: "Dr. Michael Johnson",
    image: "/images/doctor1.jpg",
    speciality: "Neurology",
    experience: "12 years",
    location: "Lalitpur",
    contact: {
      phone: "+1 555 123 4567",
      email: "michaeljohnson@example.com",
    },
    rating: 4.9,
    reviews: 140,
    consultationFee: "$180",
  },
  {
    id: 4,
    name: "Dr. Sarah Lee",
    image: "/images/doctor1.jpg",
    speciality: "Pediatrics",
    experience: "6 years",
    location: "Butwal",
    contact: {
      phone: "+1 222 333 4444",
      email: "sarahlee@example.com",
    },
    rating: 4.6,
    reviews: 110,
    consultationFee: "$130",
  },
  {
    id: 5,
    name: "Dr. David Martinez",
    image: "/images/doctor1.jpg",
    speciality: "Orthopedics",
    experience: "15 years",
    location: "Hetauda",
    contact: {
      phone: "+1 111 222 3333",
      email: "davidmartinez@example.com",
    },
    rating: 4.9,
    reviews: 160,
    consultationFee: "$250",
  },
];

export const filterCityOptions = [
  { value: "City", pos: "first" },
  { value: "Kathmandu" },
  { value: "Pokhara" },
  { value: "Lalitpur" },
  { value: "Biratnagar" },
  { value: "Birgunj" },
  { value: "Bharatpur" },
  { value: "Bhaktapur" },
  { value: "Dharan" },
  { value: "Butwal" },
  { value: "Hetauda" },
  { value: "Janakpur" },
  { value: "Dhangadhi" },
  { value: "Nepalgunj" },
  { value: "Bhimdatta" },
  { value: "Itahari" },
  { value: "Birtamod" },
  { value: "Birendranagar" },
  { value: "Kirtipur" },
  { value: "Tulsipur" },
  { value: "Tikapur" },
  { value: "Ghorahi" },
  { value: "Rajbiraj" },
  { value: "Gulariya" },
  { value: "Jaleshwor" },
  { value: "Kalaiya" },
  { value: "Malangwa" },
  { value: "Gaighat" },
  { value: "Baglung" },
  { value: "Tansen" },
  { value: "Putalibazar" },
  { value: "Damak" },
  { value: "Siraha" },
];

export const filterHospitalOptions = [
  { value: "Hospital", pos: "first" },
  { value: "Bir Hospital" },
  { value: "Tribhuvan University Teaching Hospital" },
  { value: "Nepal Mediciti Hospital" },
  { value: "Grande International Hospital" },
  { value: "Norvic International Hospital" },
  { value: "Nepal Cancer Hospital and Research Center" },
  { value: "Civil Service Hospital" },
  { value: "Patan Hospital" },
  { value: "Om Hospital & Research Center" },
  { value: "Kist Medical College and Teaching Hospital" },
  { value: "B&B Hospital" },
  { value: "Lalitpur Nursing Home" },
  { value: "Dhulikhel Hospital" },
  { value: "Manmohan Cardiothoracic Vascular and Transplant Center" },
  { value: "Shree Harsha Hospital" },
];

export const filterSpecialityOptions = [
  { value: "Speciality", pos: "first" },
  { value: "Cardiology" },
  { value: "Dermatology" },
  { value: "Endocrinology" },
  { value: "Gastroenterology" },
  { value: "Hematology" },
  { value: "Infectious Disease" },
  { value: "Nephrology" },
  { value: "Neurology" },
  { value: "Oncology" },
  { value: "Ophthalmology" },
  { value: "Orthopedics" },
  { value: "Otolaryngology" },
  { value: "Pathology" },
  { value: "Pediatrics" },
  { value: "Psychiatry" },
  { value: "Pulmonology" },
  { value: "Radiology" },
  { value: "Rheumatology" },
  { value: "Surgery" },
  { value: "Urology" },
  { value: "Anesthesiology" },
  { value: "Family Medicine" },
  { value: "Internal Medicine" },
  { value: "Obstetrics and Gynecology" },
  { value: "Plastic Surgery" },
  { value: "Emergency Medicine" },
  { value: "Geriatrics" },
  { value: "Neonatology" },
  { value: "Allergy and Immunology" },
  { value: "Sports Medicine" },
];