export const doctors_data = [
  {
    id: 1,
    name: "Dr. John Smith",
    image: "/images/doctor1.jpg",
    speciality: "Cardiologist",
    experience: "10 years",
    location: "New York, USA",
    contact: {
      phone: "+1 123 456 7890",
      email: "johnsmith@example.com",
    },
    rating: 4.8,
    reviews: 120,
    consultationFee: "$150",
  },
  {
    id: 2,
    name: "Dr. Emily Clark",
    image: "/images/doctor1.jpg",
    speciality: "Dermatologist",
    experience: "8 years",
    location: "Los Angeles, USA",
    contact: {
      phone: "+1 987 654 3210",
      email: "emilyclark@example.com",
    },
    rating: 4.7,
    reviews: 95,
    consultationFee: "$200",
  },
  {
    id: 3,
    name: "Dr. Michael Johnson",
    image: "/images/doctor1.jpg",
    speciality: "Neurologist",
    experience: "12 years",
    location: "Chicago, USA",
    contact: {
      phone: "+1 555 123 4567",
      email: "michaeljohnson@example.com",
    },
    rating: 4.9,
    reviews: 140,
    consultationFee: "$180",
  },
  {
    id: 4,
    name: "Dr. Sarah Lee",
    image: "/images/doctor1.jpg",
    speciality: "Pediatrician",
    experience: "6 years",
    location: "Houston, USA",
    contact: {
      phone: "+1 222 333 4444",
      email: "sarahlee@example.com",
    },
    rating: 4.6,
    reviews: 110,
    consultationFee: "$130",
  },
  {
    id: 5,
    name: "Dr. David Martinez",
    image: "/images/doctor1.jpg",
    speciality: "Orthopedic Surgeon",
    experience: "15 years",
    location: "Miami, USA",
    contact: {
      phone: "+1 111 222 3333",
      email: "davidmartinez@example.com",
    },
    rating: 4.9,
    reviews: 160,
    consultationFee: "$250",
  },
];
